# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        books:
            uri_prefix: /images/book
            upload_destination: '%kernel.project_dir%/public/images/book'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
